apiVersion: apps/v1
kind: Deployment
metadata:
  name: flasksklearn-hon-capstone
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: flasksklearn-hon-capstone-app
  template:
    metadata:
      name: flasksklearn-hon-capstone-pod
      labels:
        app: flasksklearn-hon-capstone-app
    spec:
      containers:
      - name: flasksklearn-hon-capstone-container
        image: hanyslmm/flasksklearn-hon-capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flasksklearn-hon-capstone-svc
  labels:
    app: flasksklearn-hon-capstone-app
spec:
  selector:
    app: flasksklearn-hon-capstone-app
  type: LoadBalancer
  ports:
  - nodePort: 30000
    port: 80
    targetPort: 80
